export default {
    darkMode: "class",
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "on-surface-variant": "#464555",
                "tertiary-fixed-dim": "#ffafd3",
                "on-primary-fixed": "#0f0069",
                "on-tertiary": "#ffffff",
                "error-container": "#ffdad6",
                "surface-container-high": "#e1e8fd",
                "on-secondary-container": "#fffbff",
                "tertiary": "#a02d6f",
                "on-primary-fixed-variant": "#321ed2",
                "on-secondary-fixed-variant": "#5516be",
                "on-primary": "#ffffff",
                "surface-container-low": "#f1f3ff",
                "surface-container-highest": "#dce2f7",
                "on-tertiary-container": "#fffafa",
                "inverse-surface": "#293040",
                "primary-fixed": "#e2dfff",
                "error": "#ba1a1a",
                "outline": "#777587",
                "primary": "#493ee5",
                "tertiary-fixed": "#ffd8e7",
                "on-error-container": "#93000a",
                "primary-fixed-dim": "#c3c0ff",
                "surface-container": "#e9edff",
                "inverse-primary": "#c3c0ff",
                "on-tertiary-fixed": "#3d0026",
                "surface-bright": "#f9f9ff",
                "outline-variant": "#c7c4d8",
                "surface-dim": "#d3daef",
                "secondary-fixed": "#e9ddff",
                "tertiary-container": "#bf4789",
                "on-background": "#141b2b",
                "surface": "#f9f9ff",
                "secondary-fixed-dim": "#d0bcff",
                "inverse-on-surface": "#edf0ff",
                "surface-container-lowest": "#ffffff",
                "on-secondary-fixed": "#23005c",
                "background": "#f9f9ff",
                "secondary-container": "#8455ef",
                "surface-variant": "#dce2f7",
                "secondary": "#6b38d4",
                "on-tertiary-fixed-variant": "#85145a",
                "surface-tint": "#4c42e9",
                "on-secondary": "#ffffff",
                "on-primary-container": "#fefaff",
                "on-error": "#ffffff",
                "primary-container": "#635bff",
                "on-surface": "#141b2b"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            spacing: {
                "space-48": "3rem",
                "space-12": "0.75rem",
                "gutter-desktop": "1.5rem",
                "space-2": "0.125rem",
                "space-40": "2.5rem",
                "space-32": "2rem",
                "space-16": "1rem",
                "gutter-mobile": "1rem",
                "space-4": "0.25rem",
                "space-8": "0.5rem",
                "space-24": "1.5rem",
                "space-64": "4rem",
                "max-width-content": "72rem"
            },
            fontFamily: {
                "headline-sm": ["Plus Jakarta Sans"],
                "display-sm": ["Plus Jakarta Sans"],
                "body-lg": ["Plus Jakarta Sans"],
                "label-sm": ["Plus Jakarta Sans"],
                "body-md": ["Plus Jakarta Sans"],
                "headline-md": ["Plus Jakarta Sans"],
                "headline-lg": ["Plus Jakarta Sans"],
                "display-lg": ["Plus Jakarta Sans"],
                "body-sm": ["Plus Jakarta Sans"],
                "label-md": ["Plus Jakarta Sans"]
            },
            fontSize: {
                "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" }],
                "display-sm": ["30px", { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "600" }],
                "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "400" }],
                "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
                "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
                "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "600" }],
                "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
                "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "400" }],
                "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }]
            }
        }
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries')
    ]
}
